import { useQuery } from "@tanstack/react-query";
import { createFileRoute } from "@tanstack/react-router";
import { Minus, Plus, ShoppingBag } from "lucide-react";
import { useState } from "react";
import { AppShell, Button, Card, Empty, ErrorState, Loading, Notice } from "../../../../shared/ui";
import { expanded, rustabase, text, type RecordRow } from "../../../../shared/rustabase";

export const Route = createFileRoute("/")({ head: () => ({ meta: [
  { title: "North Market — Everyday goods" }, { name: "description", content: "Useful goods for everyday rituals." },
  { property: "og:title", content: "North Market — Everyday goods" }, { property: "og:description", content: "Useful goods for everyday rituals." },
  { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" },
] }), component: StorePage });
type Product = RecordRow & { name?: string; price?: number; image?: string };
function StorePage() {
  const products = useQuery({ queryKey: ["products"], queryFn: () => rustabase.list<Product>("products", { filter: "active=true", sort: "name", expand: "category" }) });
  const [cart, setCart] = useState<Record<string, number>>({}); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const lines = (products.data?.items ?? []).filter((p) => cart[p.id]).map((product) => ({ product, quantity: cart[product.id] }));
  const total = lines.reduce((sum, line) => sum + Number(line.product.price || 0) * line.quantity, 0);
  const change = (id: string, by: number) => setCart((current) => ({ ...current, [id]: Math.max(0, (current[id] || 0) + by) }));
  const checkout = async () => { const user = rustabase.session()?.record; if (!user) { setMessage("Sign in before placing your order."); return; } setBusy(true); setMessage(""); try { const found = await rustabase.list<RecordRow>("customers", { filter: `email=\"${text(user.email)}\"` }); const customer = found.items[0] ?? await rustabase.create("customers", { name: text(user.email).split("@")[0], email: user.email }); await rustabase.create("orders", { customer: customer.id, total, status: "open", note: lines.map(({ product, quantity }) => `${text(product.name)} × ${quantity}`).join(", ") }); setCart({}); setMessage("Thanks — your order is confirmed."); } catch (error) { setMessage(error instanceof Error ? error.message : "Checkout failed."); } finally { setBusy(false); } };
  return <AppShell brand="North Market" eyebrow="Objects for daily life" theme="pos" auth><section><p className="eyebrow">New season</p><h1 className="display">Useful goods, thoughtfully selected.</h1><p className="lede">A small collection of lasting objects for everyday rituals.</p></section>{message ? <Notice tone={message.startsWith("Thanks") ? "success" : "danger"} onClose={() => setMessage("")}>{message}</Notice> : null}<div className="toolbar"><h2 className="section-title">The collection</h2><span className="pill"><ShoppingBag size={14} />{lines.reduce((sum, item) => sum + item.quantity, 0)} items</span></div><div className="split"><section>{products.isPending ? <Loading label="Loading products" /> : products.error ? <ErrorState error={products.error} retry={() => products.refetch()} /> : products.data.items.length === 0 ? <Empty title="Nothing on the shelf yet" detail="Add an active product in your RustaBase collection." /> : <div className="grid">{products.data.items.map((product) => <Card key={product.id}>{product.image ? <img className="cover" src={rustabase.file(product, product.image)} alt="" /> : null}<p className="meta">{text(expanded(product, "category")?.name)}</p><h3>{text(product.name)}</h3><div className="row" style={{ justifyContent: "space-between" }}><strong>${Number(product.price || 0).toFixed(2)}</strong><Button onClick={() => change(product.id, 1)}>Add</Button></div></Card>)}</div>}</section><aside className="card sticky"><h2>Your bag</h2>{lines.length === 0 ? <p className="meta">Your bag is empty.</p> : lines.map(({ product, quantity }) => <div className="cart-line" key={product.id}><span>{text(product.name)}</span><span className="row"><Button variant="quiet" aria-label={`Remove one ${text(product.name)}`} onClick={() => change(product.id, -1)}><Minus size={14} /></Button>{quantity}<Button variant="quiet" aria-label={`Add one ${text(product.name)}`} onClick={() => change(product.id, 1)}><Plus size={14} /></Button></span></div>)}<p className="price">${total.toFixed(2)}</p><Button disabled={!lines.length || busy} onClick={checkout}>{busy ? "Placing order…" : "Place order"}</Button></aside></div></AppShell>;
}
